import type { ThemeConfig } from 'antd'

export const antdTheme: ThemeConfig = {
  token: {
    colorPrimary: '#1769e0',
    colorInfo: '#1769e0',
    colorSuccess: '#1f9d67',
    colorWarning: '#d9822b',
    colorError: '#d64545',
    colorText: '#1f2a37',
    colorTextSecondary: '#5b6b80',
    colorBorder: '#dde6f2',
    colorBgBase: '#f4f7fb',
    colorBgContainer: '#ffffff',
    borderRadius: 6,
    borderRadiusLG: 8,
    fontFamily:
      "Inter, 'Segoe UI', 'PingFang SC', 'Microsoft YaHei', Arial, sans-serif",
    controlHeight: 34,
    controlHeightLG: 38,
    wireframe: false,
  },
  components: {
    Layout: {
      headerBg: '#0f5fc6',
      headerColor: '#ffffff',
      headerHeight: 60,
      headerPadding: '0 24px',
      bodyBg: '#f4f7fb',
      siderBg: '#ffffff',
      lightSiderBg: '#ffffff',
      triggerBg: '#ffffff',
      lightTriggerBg: '#ffffff',
    },
    Menu: {
      itemBorderRadius: 6,
      itemSelectedBg: '#e8f1ff',
      itemSelectedColor: '#1769e0',
      itemHoverBg: '#f3f7ff',
      itemHoverColor: '#0f4fb4',
    },
    Card: {
      headerBg: '#ffffff',
      headerFontSize: 15,
      headerHeight: 48,
      headerPadding: 20,
      bodyPadding: 20,
    },
    Table: {
      headerBg: '#f6f9ff',
      headerColor: '#334155',
      headerSplitColor: '#dde6f2',
      rowHoverBg: '#f7fbff',
      borderColor: '#e4ebf5',
      cellPaddingBlock: 13,
      cellPaddingInline: 16,
      cellPaddingBlockMD: 11,
      cellPaddingInlineMD: 14,
      headerBorderRadius: 6,
    },
    Button: {
      fontWeight: 500,
      defaultBg: '#ffffff',
      defaultBorderColor: '#c8d6e8',
      defaultColor: '#334155',
      defaultHoverBg: '#f7fbff',
      defaultHoverBorderColor: '#1769e0',
      defaultHoverColor: '#1769e0',
      defaultShadow: 'none',
      primaryShadow: '0 8px 16px rgba(23, 105, 224, 0.18)',
    },
  },
}
